service: my-app

useDotenv: true

package:
  individually: true
  patterns:
    - '!**/*'                          # exclude everything first
    - 'handlers/**'                    # include handlers
    - 'src/**'                         # include src
    - '!node_modules/**'               # exclude all node_modules
    - 'node_modules/.prisma/**'        # include prisma binary
    - 'node_modules/@prisma/client/**' # include prisma client
    - 'src/generated/prisma/**'        # include generated prisma
    - '!.git/**'                       # exclude git
    - '!.env'                          # exclude env
    - '!README.md'                     # exclude readme
    - '!*.test.ts'                     # exclude tests

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: dev
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_REFRESH_SECRET: ${env:JWT_REFRESH_SECRET}
    SQS_QUEUE_URL: !Ref OTPQueue
    FROM_EMAIL: ${env:FROM_EMAIL}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource: !GetAtt OTPQueue.Arn
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "*"


functions:
  register:
    handler: handlers/register.handler
    events:
      - http:
          path: /api/v1/auth/register
          method: post
          cors: true
  login:
    handler: handlers/login.handler
    events:
      - http:
          path: /api/v1/auth/login
          method: post
          cors: true
  sendOTP:
    handler: handlers/sendOtp.handler
    events:
      - sqs:
          arn: !GetAtt OTPQueue.Arn
          batchSize: 10

resources:
  Resources:
    OTPQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: otp-queue
        VisibilityTimeout: 30
        MessageRetentionPeriod: 3600 

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild   
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0      
    httpPort: 3000

esbuild:
    bundle: true
    minify: true
    target: node18
    external:
      - '@prisma/client'
      - '.prisma/client'